### ISSUE TITLE
关于订阅问题

### ISSUE THREAD

**Issue by LSGLSH** [LambdaYH/zhenxun_plugin_weibo#1]
请问是只能订阅介绍里面的那四个吗

**Comment by LambdaYH** [comment]
不是，可以自己更改目录下的`weibo_config.yaml`来添加订阅项，介绍里面只是告诉你每个项是做什么用的。具体如何添加可以直接仿照`weibo_config.yaml`更改。
只需要获取用户uid即可，获取uid方法已在https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/bf652ee9786345df562368487257c0f368c3545a 中加上：[获取uid](https://github.com/LambdaYH/zhenxun_plugin_weibo#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96user_id)

> ps: 最新commit的中已经将旧版`weibo_config.json`替换为`weibo_config.yaml`

**Comment by LSGLSH** [comment]
> 不是，可以自己更改目录下的`weibo_config.yaml`来添加订阅项，介绍里面只是告诉你每个项是做什么用的。具体如何添加可以直接仿照`weibo_config.yaml`更改。 只需要获取用户uid即可，获取uid方法已在[bf652ee](https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/bf652ee9786345df562368487257c0f368c3545a) 中加上：[获取uid](https://github.com/LambdaYH/zhenxun_plugin_weibo#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96user_id)
> 
> > ps: 最新commit的中已经将旧版`weibo_config.json`替换为`weibo_config.yaml`

了解，大致已经明白了，目前正在修改

**Comment by eyelc** [comment]
请问能正确获取微博内容，但是无法推送，报错：UnboundLocalError: local variable 'page' referenced before assignment

**Comment by LambdaYH** [comment]
> 请问能正确获取微博内容，但是无法推送，报错：UnboundLocalError: local variable 'page' referenced before assignment

放到新issue里讨论，顺便贴一下日志和目标微博用户ID，我方便调试
