### ISSUE TITLE
真寻更新之后的报错

### ISSUE THREAD

**Issue by 15220526** [LambdaYH/zhenxun_plugin_weibo#10]
请问这是什么问题呢
![image](https://user-images.githubusercontent.com/106159640/225531808-a2a994d4-72e1-4e7d-ad03-b09057a5d4a8.png)
![image](https://user-images.githubusercontent.com/106159640/225531974-3f044125-c370-469e-a0f7-e262f1d5abba.png)

**Comment by LambdaYH** [comment]
https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/ab60a27039cd9a0241f45ef93a2c351e7373cdb1

也许应该修好了，逝世新版
