### ISSUE TITLE
问个蠢问题，怎么开启

### ISSUE THREAD

**Issue by 534019023** [LambdaYH/zhenxun_plugin_weibo#12]
![image](https://user-images.githubusercontent.com/95991937/230752992-06abc0f6-c400-4155-a148-28c10a1c609d.png)

订阅列表全是我自己加的，默认全关闭的，我怎么都触发不了开启的指令
个人不太懂代码，但看了下init文件里也没有开启的指令触发
请问是代码里没加吗，还是说我指令格式问题

**Comment by LambdaYH** [comment]
啊....  指令里是不包含`[`和`]`的

这个插件的控制是和真寻的`群被动状态`对接的
可以发送`群被动状态`查看状态。

假如你设置了一个`abc微博推送`，
那么开启指令就是`开启abc微博推送`

> 如果是添加后的第一次启动可能需要重启一下Bot

**Comment by 534019023** [comment]
> 啊.... 指令里是不包含`[`和`]`的
> 
> 这个插件的控制是和真寻的`群被动状态`对接的 可以发送`群被动状态`查看状态。
> 
> 假如你设置了一个`abc微博推送`， 那么开启指令就是`开启abc微博推送`

原来是我多加了个空格，谢谢，真抱歉打扰了

**Comment by LambdaYH** [comment]
> 

好像是我在这个`可订阅微博列表`里多加了个空格（，由于自己改过了让加空格也能触发所以没注意

**Comment by 534019023** [comment]
> > 
> 
> 好像是我在这个`可订阅微博列表`里多加了个空格（，由于自己改过了让加空格也能触发所以没注意

我确实有点被这个图片上的指令误导了
