### ISSUE TITLE
有一个微博号一使用会出现以下的报错

### ISSUE THREAD

**Issue by 15220526** [LambdaYH/zhenxun_plugin_weibo#13]
这个迷惑行为的id是5594559637
![image](https://user-images.githubusercontent.com/106159640/231079002-4e91a5d0-af94-4967-92c2-6231e74ad3fd.png)
这个是我在文件夹下yaml的设置
![image](https://user-images.githubusercontent.com/106159640/231079447-a62f06aa-29c5-4fd7-94be-e725fd69d361.png)
其他的微博号都是没有问题的，请问这是怎么回事呢

**Comment by LambdaYH** [comment]
试一下把`resources / temp / weibo / 5594559637.json ` 删掉后重启

**Comment by 15220526** [comment]
感谢，解决了不过又出现了这个报错，这会影响插件运行吗
![J034OG5$6T@8V}WK$IJGL)C](https://user-images.githubusercontent.com/106159640/231081160-9581c387-5532-4fbc-ac97-a379669b5e8f.png)

**Comment by LambdaYH** [comment]
这主要是bot所在网络和微博那边联通性问题，只要不是一直失败导致无法推送就无所谓

**Comment by 15220526** [comment]
好的明白了
