### ISSUE TITLE
请问能正确获取微博内容，但是无法推送，报错：UnboundLocalError: local variable 'page' referenced before assignment

### ISSUE THREAD

**Issue by LambdaYH** [LambdaYH/zhenxun_plugin_weibo#2]
请问能正确获取微博内容，但是无法推送，报错：UnboundLocalError: local variable 'page' referenced before assignment

_Originally posted by @eyelc in https://github.com/LambdaYH/zhenxun_plugin_weibo/issues/1#issuecomment-1272501411_

**Comment by LambdaYH** [comment]
[@eyelc](https://github.com/eyelc) 猜测是你真寻本体的playwright部分安装有问题

**Comment by eyelc** [comment]
谢谢，我先检查一下看playwright，如果不行我再把日志贴出来

**Comment by eyelc** [comment]
> [@eyelc](https://github.com/eyelc) 猜测是你真寻本体的playwright部分安装有问题

还是同样错误，麻烦看一下什么原因，谢谢！
环境：Python 3.8.5    playwright已重装，版本号：1.27.0
目标微博id：1862172703
真寻启动时有一条警告信息：
/home/wwwroot/zhenxun_bot/plugins/weibo/weibo_spider.py:213: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not selector:
日志：
10-09 18:06:32 [ERROR] apscheduler | Job "_ (trigger: interval[0:02:00], next run at: 2022-10-09 18:08:26 CST)" raised an exception
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f26e7df84c0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f26ef2ad160>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x7f26e60f2af0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f26e60f2ca0>
    └ <uvicorn.server.Server object at 0x7f26c8d820d0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f26e60f2d30>
           │       │   └ <uvicorn.server.Server object at 0x7f26c8d820d0>
           │       └ <function run at 0x7f26ec1470d0>
           └ <module 'asyncio' from '/.pyenv/versions/3.8.5/lib/python3.8/asyncio/__init__.py'>
  File "/.pyenv/versions/3.8.5/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f26c8d393c0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>

  File "/home/wwwroot/zhenxun_bot/plugins/weibo/__init__.py", line 230, in _
    formatted_weibos = [(await process_wb(format, wb)) for wb in latest_weibos]
                               │          │                      └ [{'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月3...
                               │          └ 1
                               └ <function process_wb at 0x7f26c8d983a0>

  File "/home/wwwroot/zhenxun_bot/plugins/weibo/__init__.py", line 230, in <listcomp>
    formatted_weibos = [(await process_wb(format, wb)) for wb in latest_weibos]
                               │          │       │        └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
                               │          │       └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
                               │          └ 1
                               └ <function process_wb at 0x7f26c8d983a0>

  File "/home/wwwroot/zhenxun_bot/plugins/weibo/__init__.py", line 218, in process_wb
    if format == 1 and (msg := await wb_to_image(wb)):
       │                             │           └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
       │                             └ <function wb_to_image at 0x7f26c8d98310>
       └ 1

  File "/home/wwwroot/zhenxun_bot/plugins/weibo/__init__.py", line 212, in wb_to_image
    if page:

UnboundLocalError: local variable 'page' referenced before assignment

**Comment by LambdaYH** [comment]
> > [@eyelc](https://github.com/eyelc) 猜测是你真寻本体的playwright部分安装有问题
> 
> 还是同样错误，麻烦看一下什么原因，谢谢！ 环境：Python 3.8.5 playwright已重装，版本号：1.27.0 目标微博id：1862172703 真寻启动时有一条警告信息： /home/wwwroot/zhenxun_bot/plugins/weibo/weibo_spider.py:213: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead. if not selector: 日志： 10-09 18:06:32 [ERROR] apscheduler | Job "_ (trigger: interval[0:02:00], next run at: 2022-10-09 18:08:26 CST)" raised an exception Traceback (most recent call last):
> 
> File "bot.py", line 21, in nonebot.run() │ └ <function run at 0x7f26e7df84c0> └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/__in...
> 
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/**init**.py", line 261, in run get_driver().run(*args, **kwargs) │ │ └ {} │ └ () └ <function get_driver at 0x7f26ef2ad160> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run uvicorn.run( │ └ <function run at 0x7f26e60f2af0> └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/__in... File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run server.run() │ └ <function Server.run at 0x7f26e60f2ca0> └ <uvicorn.server.Server object at 0x7f26c8d820d0> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) │ │ │ │ └ None │ │ │ └ <function Server.serve at 0x7f26e60f2d30> │ │ └ <uvicorn.server.Server object at 0x7f26c8d820d0> │ └ <function run at 0x7f26ec1470d0> └ <module 'asyncio' from '/.pyenv/versions/3.8.5/lib/python3.8/asyncio/**init**.py'> File "/.pyenv/versions/3.8.5/lib/python3.8/asyncio/runners.py", line 43, in run return loop.run_until_complete(main) │ │ └ <coroutine object Server.serve at 0x7f26c8d393c0> │ └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects> └ <uvloop.Loop running=True closed=False debug=False>
> 
> > File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-hgx9rJ9R-py3.8/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
> > retval = await job.func(*job.args, **job.kwargs)
> > │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
> > │   │     │   │       └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>
> > │   │     │   └ <member 'args' of 'Job' objects>
> > │   │     └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>
> > │   └ <member 'func' of 'Job' objects>
> > └ <Job (id=2fbd007269be412c94a97bc3bfd1d38b name=_)>
> 
> File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 230, in _ formatted_weibos = [(await process_wb(format, wb)) for wb in latest_weibos] │ │ └ [{'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月3... │ └ 1 └ <function process_wb at 0x7f26c8d983a0>
> 
> File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 230, in formatted_weibos = [(await process_wb(format, wb)) for wb in latest_weibos] │ │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30... │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30... │ └ 1 └ <function process_wb at 0x7f26c8d983a0>
> 
> File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb if format == 1 and (msg := await wb_to_image(wb)): │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30... │ └ <function wb_to_image at 0x7f26c8d98310> └ 1
> 
> File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 212, in wb_to_image if page:
> 
> UnboundLocalError: local variable 'page' referenced before assignment

10-09 18:06:32 [ERROR] apscheduler | Job "_ (trigger: interval[0:02:00], next run at: 2022-10-09 18:08:26 CST)" raised an exception
Traceback (most recent call last):
这一行前面有类似`"截取微博主页失败:`的日志吗

**Comment by eyelc** [comment]
没有，上面也是一样的，另外一条获取到内容的

**Comment by LambdaYH** [comment]
![image](https://user-images.githubusercontent.com/13503375/194753214-4bb5c138-028d-4498-acc1-f60247989075.png)
你上面报错的这条微博我这里可以正常获取，很疑惑

**Comment by eyelc** [comment]
> ![image](https://user-images.githubusercontent.com/13503375/194753214-4bb5c138-028d-4498-acc1-f60247989075.png) 你上面报错的这条微博我这里可以正常获取，很疑惑

我只有再试试了，谢谢

**Comment by LambdaYH** [comment]
> File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> if format == 1 and (msg := await wb_to_image(wb)):
> │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> │ └ <function wb_to_image at 0x7f26c8d98310>

你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。
但是你上面的报错我几乎可以断定是
https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
这几行的错，但是这几行错就意味着是playwright的问题：没获取到浏览器

**Comment by LambdaYH** [comment]
> > ![image](https://user-images.githubusercontent.com/13503375/194753214-4bb5c138-028d-4498-acc1-f60247989075.png) 你上面报错的这条微博我这里可以正常获取，很疑惑
> 
> 我只有再试试了，谢谢

如果不强求图片形式推送也可以在找到问题前先改成文本模式，文本模式一定是正常的（

**Comment by eyelc** [comment]
> > File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> > if format == 1 and (msg := await wb_to_image(wb)):
> > │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> > │ └ <function wb_to_image at 0x7f26c8d98310>
> 
> 你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。 但是你上面的报错我几乎可以断定是
> 
> https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
> 
> 
> 这几行的错，但是这几行错就以为着是playwright的问题：没获取到浏览器

B站订阅没有用，我试一下看看。
我文本也试一下。
控件除了weibo_config.yaml里按格式加入自己的目标微博id，其他地方不用设置啥了吧？

**Comment by LambdaYH** [comment]
> > > File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> > > if format == 1 and (msg := await wb_to_image(wb)):
> > > │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> > > │ └ <function wb_to_image at 0x7f26c8d98310>
> > 
> > 
> > 你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。 但是你上面的报错我几乎可以断定是
> > https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
> > 
> > 这几行的错，但是这几行错就以为着是playwright的问题：没获取到浏览器
> 
> B站订阅没有用，我试一下看看。 我文本也试一下。 控件除了weibo_config.yaml里按格式加入自己的目标微博id，其他地方不用设置啥了吧？

看你这日志应该`weibo_config.yaml`是没问题的。



> 没有，上面也是一样的，另外一条获取到内容的

你这里说的另外一条获取到内容的是成功推送出来了吗

**Comment by eyelc** [comment]
> > > > File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> > > > if format == 1 and (msg := await wb_to_image(wb)):
> > > > │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> > > > │ └ <function wb_to_image at 0x7f26c8d98310>
> > > 
> > > 
> > > 你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。 但是你上面的报错我几乎可以断定是
> > > https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
> > > 
> > > 这几行的错，但是这几行错就以为着是playwright的问题：没获取到浏览器
> > 
> > 
> > B站订阅没有用，我试一下看看。 我文本也试一下。 控件除了weibo_config.yaml里按格式加入自己的目标微博id，其他地方不用设置啥了吧？
> 
> 看你这日志应该`weibo_config.yaml`是没问题的。
> 
> > 没有，上面也是一样的，另外一条获取到内容的
> 
> 你这里说的另外一条获取到内容的是成功推送出来了吗

没有推出来，一样的问题

**Comment by LambdaYH** [comment]
> > > > > File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> > > > > if format == 1 and (msg := await wb_to_image(wb)):
> > > > > │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> > > > > │ └ <function wb_to_image at 0x7f26c8d98310>
> > > > 
> > > > 
> > > > 你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。 但是你上面的报错我几乎可以断定是
> > > > https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
> > > > 
> > > > 这几行的错，但是这几行错就以为着是playwright的问题：没获取到浏览器
> > > 
> > > 
> > > B站订阅没有用，我试一下看看。 我文本也试一下。 控件除了weibo_config.yaml里按格式加入自己的目标微博id，其他地方不用设置啥了吧？
> > 
> > 
> > 看你这日志应该`weibo_config.yaml`是没问题的。
> > > 没有，上面也是一样的，另外一条获取到内容的
> > 
> > 
> > 你这里说的另外一条获取到内容的是成功推送出来了吗
> 
> 没有推出来，一样的问题

十分觉得就是你playwright所需的浏览器没有安装成功
可以用真寻其他用到playwright的插件测试下
例如，发送`原神黄历`试试

**Comment by eyelc** [comment]
> > > > > > File "/home/wwwroot/zhenxun_bot/plugins/weibo/**init**.py", line 218, in process_wb
> > > > > > if format == 1 and (msg := await wb_to_image(wb)):
> > > > > > │ │ └ {'screen_name': '集微网官方微博', 'id': '4822720380666156', 'bid': 'M9x3M2Nis', 'text': '【#深圳市战略性新兴产业扶持计划拟资助项目公示#，含9个集成电路项目】\n\n9月30...
> > > > > > │ └ <function wb_to_image at 0x7f26c8d98310>
> > > > > 
> > > > > 
> > > > > 你真寻的B站订阅那些正常吗，如果那些正常后就可以确定你的playwright没问题。 但是你上面的报错我几乎可以断定是
> > > > > https://github.com/LambdaYH/zhenxun_plugin_weibo/blob/81a42448eb976ab87d23f98caa163bc9e0ffd9ec/__init__.py#L187-L189
> > > > > 
> > > > > 这几行的错，但是这几行错就以为着是playwright的问题：没获取到浏览器
> > > > 
> > > > 
> > > > B站订阅没有用，我试一下看看。 我文本也试一下。 控件除了weibo_config.yaml里按格式加入自己的目标微博id，其他地方不用设置啥了吧？
> > > 
> > > 
> > > 看你这日志应该`weibo_config.yaml`是没问题的。
> > > > 没有，上面也是一样的，另外一条获取到内容的
> > > 
> > > 
> > > 你这里说的另外一条获取到内容的是成功推送出来了吗
> > 
> > 
> > 没有推出来，一样的问题
> 
> 十分觉得就是你playwright所需的浏览器没有安装成功 可以用真寻其他用到playwright的插件测试下 例如，发送`原神黄历`试试

好的，谢谢
