### ISSUE TITLE
请问一下COOKIE是填哪个字段？

### ISSUE THREAD

**Issue by Nenot233** [LambdaYH/zhenxun_plugin_weibo#3]

**Comment by Nenot233** [comment]
还是整段COOKIE就行？

**Comment by LambdaYH** [comment]
一整段就行

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/198565371-4ef200bf-d13b-4dc5-bbf8-93be81b619d8.png)
是这里面其中一段？
![image](https://user-images.githubusercontent.com/108965579/198565612-e853e7b5-7e40-4810-ada3-c2661d224c10.png)
还是这里面一大段全部复制过去？
我复制的是整一大段，关闭之后会自动换行，会有影响吗
![image](https://user-images.githubusercontent.com/108965579/198566876-ed7b301d-7b66-4a5c-85a4-8ab2d32356cc.png)
因为试了之后发现不会推送仅粉丝可见的微博，所以有疑惑

**Comment by LambdaYH** [comment]
试试看如下步骤
1. 去[https://passport.weibo.cn/signin/login](https://passport.weibo.cn/signin/login)登录
2. 访问[https://m.weibo.cn/](https://m.weibo.cn/)
3. 开F12，复制红框那一串
![image](https://user-images.githubusercontent.com/13503375/198578656-faebc49a-910d-4b15-a4e0-82b5603d2f01.png)

我刚刚去测试了一下可以正常获取的
> ps: 仅粉丝可见的微博无法截图推送而只能以文本形式
