### ISSUE TITLE
微博推送报错问题

### ISSUE THREAD

**Issue by LSGLSH** [LambdaYH/zhenxun_plugin_weibo#8]
新版本和老版本我的微博推送都出现了同一个报错，请问可以留个联系方式，方便发送多个报错截图吗

**Comment by LambdaYH** [comment]
直接在这个issue里发截图吧

**Comment by LSGLSH** [comment]
> 直接在这个issue里发截图吧

截图过于长，issue不太方便。。。我留个我QQ吧2368343278，我在真寻的群里找不到作者，只能这样联系了
