### ISSUE TITLE
被动无法默认关闭

### ISSUE THREAD

**Issue by Nenot233** [LambdaYH/zhenxun_plugin_weibo#9]
weibo-15eve:
  desciption: 15微博推送
  enable_on_default: False
  format: 0
  users:
  - user_id: '7817226432'
    nickname: 伊舞Eve
    filter_retweet: false
    filter_words: [
    微博抽奖平台,
    微博会员
    ]
 yaml配置文件
 以及推送无法识别是否以转发模式推送微博
 zhenxun_plugin_weibo:
  # 微博推送
  # FORWARD_MODE: 是否以转发模式推送微博，当配置项为true时将以转发模式推送
  # DEFAULT_FORMAT: 默认推送格式：0 文本，1 图片
  # COOKIE: 添加cookie后可以获取到更多的微博
  FORWARD_MODE: false
  DEFAULT_FORMAT: 1

**Comment by Nenot233** [comment]
截止23/03/02最新真寻版本

**Comment by LambdaYH** [comment]
看了下感觉应该是真寻的问题，不光这个的config里面没有value了，其他插件原先的值也部分消失了，以下是几个我发现的，右侧为原配置，左侧为更新后生成的新配置（要不是这个issue我都完全没发现
![image](https://user-images.githubusercontent.com/13503375/222374383-c70cae31-e8ed-4399-b33b-fa33a1811eb4.png)
![image](https://user-images.githubusercontent.com/13503375/222374457-75e32b20-b595-4fa3-9dd3-123bc96e8a8c.png)
![image](https://user-images.githubusercontent.com/13503375/222374456-28b45d73-14e5-4ac6-812d-c4bbbfe20bc7.png)
![image](https://user-images.githubusercontent.com/13503375/222374490-22f16050-ea89-4824-8b63-cb48f38b0df9.png)


而且消失的只有false

**Comment by Nenot233** [comment]
奇怪的是，原先的值能生效，后面加的一个不生效false

**Comment by LambdaYH** [comment]
因为真寻对于默认的逻辑是仅仅对新加的群生效，曾经的群保留原配置。所以只要在加群的那个时候被设定为false，那么后面即使改成true，那个群依旧是false，可以看看`/data/manager/group_manager.json`文件

**Comment by LambdaYH** [comment]
https://github.com/HibiKier/zhenxun_bot/pull/1288
等真寻吃了这个pr后重新生成配置应该就好了
